### ISSUE TITLE
examples blocks (====) preceeded by .title are rendered as figures

### ISSUE THREAD

**Issue by nicolastaffin** [jirutka/asciidoctor-html5#18]
Hi, another issue about example blocks (i did not check with another block type) when they are preceeded by a .title

```
====
This is an example
====
```

is rendered as:

`<div class="example-block"><div class="example"><p>This is an example</p></div></div>
`

but 

```
.my nice example
====
This is an example
====
```

generates a figure:

```
<figure class="example-block"><figcaption>Example 1. my nice example</figcaption>
<div class="example"><p>This is an example</p></div></figure>

```

where i would expect more:

`<div class="example-block"><div class="example"><h6 class="block-title">my nice example</h6><p>This is an example</p></div></div>
`

is there something wrong about titling a block ?

**Comment by jirutka** [comment]
This is not a bug, but feature. What do you dislike about it?
