### ISSUE TITLE
converter file is missing

### ISSUE THREAD

**Issue by caifara** [jirutka/asciidoctor-html5#3]
`lib/asciidoctor/html5s.rb` contains a line `require 'asciidoctor/html5s/converter'` but this file does not exist.

After commenting the line I get: `missing converter for backend 'html5s'` as the next error.

**Comment by jirutka** [comment]
File `asciidoctor/html5s/converter.rb` is generated from the Slim templates and it’s included in released packages. If you use it directly from git, run `rake build` to generate the converter file.

**Comment by jirutka** [comment]
Also I’m sorry for very late response, I somehow missed notification about new issue. 😿
